### ISSUE TITLE
Dichiarazione di Riuso Software Regione Puglia

### ISSUE THREAD

**Issue by alagatta** [regione-marche/meetpad-public#5]
Buongiorno sono un dipendente di Engineering II s.p.a e scrivo per conto della Regione Puglia.

Si comunica che il software è in riuso presso Regione Puglia, pertanto si richiede l'inserimento del codice IPA r_puglia all'interno del file publiccode.yml come indicato al sito https://developers.italia.it/.

Saluti.

**Comment by christiandeangelis** [comment]
Buongiorno, provvediamo all'inserimento delle informazioni.
Grazie,
Christian

**Comment by christiandeangelis** [comment]
L'ente Regione Puglia è stata inserito nella lista delle amministrazioni che utilizzano la piattaforma Meetpad. La modifica è stata recepita da Developers Italia.
